//Tests to see if the CRUD is working

###
GET http://localhost:9000/api/comuna HTTP/1.1

###
POST http://localhost:9000/api/comuna HTTP/1.1
Content-Type: application/json

{
    "id_comuna" : 6,
    "nom_comuna": "jamon"
}

###
DELETE http://localhost:9000/api/comuna/3 HTTP/1.1

###
PUT http://localhost:9000/api/comuna/3 HTTP/1.1
Content-Type: application/json

{
    "nom_comuna": "maipu"
}